SQLite:
  SQLiteLocate: data.db
MySQL:
  Server: 'localhost'
  Port: 3306
  Database: 'playerrolechecker'
  Username: 'playerrolecheckeruser'
  Password: 'playerrolecheckerpass'
  Option: '?allowPublicKeyRetrieval=true&useSSL=false'
## DiscordToken: DiscordBotのトークン
## AdminChannel: (チャンネルID) アドミンチャンネル(必要ではない)
## ChannelID: チャンネルID(必要ないがほぼ必須)
Discord:
  DiscordToken: TokenHere
  AdminChannel:
  ChannelID: