SQLite:
  SQLiteLocate: data.db
MySQL:
  Server: 'localhost'
  Port: 3306
  Database: 'playerrolechecker'
  Username: 'playerrolecheckeruser'
  Password: 'playerrolecheckerpass'
  Option: '?allowPublicKeyRetrieval=true&useSSL=false'
  UseSQLDebug: false
## DiscordToken: DiscordBotのトークン
## ChannelID: チャンネルID(必要ないがほぼ必須)
Discord:
  DiscordToken: TokenHere
  ChannelID: