SQLite:
  SQLiteLocate: data.db
MySQL:
  Server: 'localhost'
  Port: 3306
  Database: 'playerrolechecker'
  Username: 'playerrolecheckeruser'
  Password: 'playerrolecheckerpass'
  Option: '?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=latin1&autoReconnect=true'
## DiscordToken: DiscordBotのトークン
## AdminChannel: (チャンネルID) アドミンチャンネル(必要ではない)
## ChannelID: チャンネルID(必要ないがほぼ必須)
## addToRole: 登録が完了したらつけるロール (1個のみ）
Discord:
  DiscordToken: TokenHere
  AdminChannel:
  ChannelID:
  addToRole: