MySQL:
  Server: 'localhost'
  Port: 3306
  Database: 'playerrolechecker'
  Username: 'playerrolecheckeruser'
  Password: 'playerrolecheckerpass'
  Option: '?allowPublicKeyRetrieval=true&useSSL=false'
  UseSQLDebug: false
## DiscordToken: DiscordBotのトークン
## GuildID: GuildID(必須ではない)
Discord:
  DiscordToken: TokenHere
  RoleID: