MySQL:
  Server: 'localhost'
  Port: 3306
  Database: 'playerrolechecker'
  Username: 'playerrolecheckeruser'
  Password: 'playerrolecheckerpass'
  Option: '?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=latin1'
  UseSQLDebug: false
## DiscordToken: DiscordBotのトークン
## RoleID: RoleID(必須)
## GuildID: GuildID(後で書くので今は必須ではない)
Discord:
  DiscordToken: TokenHere
  GuildID:
  RoleID:
    - null1
    - null2