SQLite:
  SQLiteLocate: bypass.db
MySQL:
  Server: 'localhost'
  Port: 3306
  Database: 'playerrolechecker'
  Username: 'playerrolecheckeruser'
  Password: 'playerrolecheckerpass'
  Option: '?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=latin1&autoReconnect=true'
  UseSQLDebug: false
## JoinCommand: プレイヤーが参加したときにコマンドを打ちます
## %name% - プレイヤー名
## %uuid% - UUID
## JoinCommand:
## - 'COMMAND HERE'
JoinCommand:
## DiscordToken: DiscordBotのトークン
## RoleID: RoleID(必須)
## GuildID: GuildID(必須ではない)
Discord:
  DiscordToken: TokenHere
  GuildID:
  RoleID:
    - roleid1
    - roleid2
## Minecraft: 参加メッセージ
## %name% - プレイヤー名
## %uuid% - UUID
## %discordid% - discordID
## %role% - role
Minecraft:
  kickMessage:
    line1: '&6あなたには参加権限がありません。'
    line2: '&bDiscordを確認してみてください。'
  joinMessage: '&a%name%&fが入室しました'
  message:
    - '&a-----------------情報------------------'
    - 'MinecraftName: %name%'
    - 'DiscordID: %discordid%'
    - 'DiscordRole: %role%'
    - '&a-------------------------------------'